name: Nexus Front End Prod Deployment
env:
  VERCEL_ORD_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches: [master]

jobs:
  deploy:
    if: github.repository == 'Shivam5560/nexus_fe'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install Vercel CLI
        run: npm install --global vercel@latest

      - name: pull Vercel environment information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: build project artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: deploy project artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
